// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package org.omg.sysml.metamodel;

import java.util.Collection;
import java.util.List;
import java.util.Set;

public interface AcceptActionUsage extends ActionUsage, SysMLType {
    Expression getPayloadArgument();

    ReferenceUsage getPayloadParameter();

    Expression getReceiverArgument();
}