// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package org.omg.sysml.metamodel;

import java.util.Collection;
import java.util.List;
import java.util.Set;

public interface ConjugatedPortTyping extends FeatureTyping, SysMLType {
    ConjugatedPortDefinition getConjugatedPortDefinition();

    PortDefinition getPortDefinition();
}