// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package org.omg.sysml.metamodel;

import java.util.Collection;
import java.util.List;
import java.util.Set;

public interface Connector extends Feature, Relationship, SysMLType {
    List<? extends Association> getAssociation();

    List<? extends Feature> getConnectorEnd();

    Type getDefaultFeaturingType();

    List<? extends Feature> getRelatedFeature();

    Feature getSourceFeature();

    List<? extends Feature> getTargetFeature();
}