// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package org.omg.sysml.metamodel;

import java.util.Collection;
import java.util.List;
import java.util.Set;

public interface Element extends SysMLType {
    List<? extends String> getAliasIds();

    String getDeclaredName();

    String getDeclaredShortName();

    List<? extends Documentation> getDocumentation();

    java.util.UUID getElementId();

    Boolean getIsImpliedIncluded();

    Boolean getIsLibraryElement();

    String getName();

    List<? extends Annotation> getOwnedAnnotation();

    List<? extends Element> getOwnedElement();

    List<? extends Relationship> getOwnedRelationship();

    Element getOwner();

    OwningMembership getOwningMembership();

    Namespace getOwningNamespace();

    Relationship getOwningRelationship();

    String getQualifiedName();

    String getShortName();

    List<? extends TextualRepresentation> getTextualRepresentation();
}