// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package org.omg.sysml.metamodel;

import java.util.Collection;
import java.util.List;
import java.util.Set;

public interface Feature extends Type, SysMLType {
    List<? extends Feature> getChainingFeature();

    Feature getCrossFeature();

    FeatureDirectionKind getDirection();

    Type getEndOwningType();

    Feature getFeatureTarget();

    List<? extends Type> getFeaturingType();

    Boolean getIsComposite();

    Boolean getIsConstant();

    Boolean getIsDerived();

    Boolean getIsEnd();

    Boolean getIsOrdered();

    Boolean getIsPortion();

    Boolean getIsUnique();

    Boolean getIsVariable();

    CrossSubsetting getOwnedCrossSubsetting();

    List<? extends FeatureChaining> getOwnedFeatureChaining();

    Collection<? extends FeatureInverting> getOwnedFeatureInverting();

    Collection<? extends Redefinition> getOwnedRedefinition();

    ReferenceSubsetting getOwnedReferenceSubsetting();

    Collection<? extends Subsetting> getOwnedSubsetting();

    List<? extends TypeFeaturing> getOwnedTypeFeaturing();

    List<? extends FeatureTyping> getOwnedTyping();

    FeatureMembership getOwningFeatureMembership();

    Type getOwningType();

    List<? extends Type> getType();
}