// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package org.omg.sysml.metamodel;

import java.util.Collection;
import java.util.List;
import java.util.Set;

public interface Namespace extends Element, SysMLType {
    List<? extends Membership> getImportedMembership();

    List<? extends Element> getMember();

    List<? extends Membership> getMembership();

    List<? extends Import> getOwnedImport();

    List<? extends Element> getOwnedMember();

    List<? extends Membership> getOwnedMembership();
}