// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package org.omg.sysml.metamodel;

import java.util.Collection;
import java.util.List;
import java.util.Set;

public interface RequirementDefinition extends ConstraintDefinition, SysMLType {
    List<? extends PartUsage> getActorParameter();

    List<? extends ConstraintUsage> getAssumedConstraint();

    List<? extends ConcernUsage> getFramedConcern();

    String getReqId();

    List<? extends ConstraintUsage> getRequiredConstraint();

    List<? extends PartUsage> getStakeholderParameter();

    Usage getSubjectParameter();

    Collection<? extends String> getText();
}