// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package org.omg.sysml.metamodel;

import java.util.Collection;
import java.util.List;
import java.util.Set;

public interface StateUsage extends ActionUsage, SysMLType {
    ActionUsage getDoAction();

    ActionUsage getEntryAction();

    ActionUsage getExitAction();

    Boolean getIsParallel();

    List<? extends Behavior> getStateDefinition();
}