// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package org.omg.sysml.metamodel;

import java.util.Collection;
import java.util.List;
import java.util.Set;

public interface Type extends Namespace, SysMLType {
    List<? extends Type> getDifferencingType();

    List<? extends Feature> getDirectedFeature();

    List<? extends Feature> getEndFeature();

    List<? extends Feature> getFeature();

    List<? extends FeatureMembership> getFeatureMembership();

    List<? extends Feature> getInheritedFeature();

    List<? extends Membership> getInheritedMembership();

    List<? extends Feature> getInput();

    List<? extends Type> getIntersectingType();

    Boolean getIsAbstract();

    Boolean getIsConjugated();

    Boolean getIsSufficient();

    Multiplicity getMultiplicity();

    List<? extends Feature> getOutput();

    Conjugation getOwnedConjugator();

    List<? extends Differencing> getOwnedDifferencing();

    Collection<? extends Disjoining> getOwnedDisjoining();

    List<? extends Feature> getOwnedEndFeature();

    List<? extends Feature> getOwnedFeature();

    List<? extends FeatureMembership> getOwnedFeatureMembership();

    List<? extends Intersecting> getOwnedIntersecting();

    List<? extends Specialization> getOwnedSpecialization();

    List<? extends Unioning> getOwnedUnioning();

    List<? extends Type> getUnioningType();
}