// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package org.omg.sysml.metamodel;

import java.util.Collection;
import java.util.List;
import java.util.Set;

public interface Usage extends Feature, SysMLType {
    List<? extends Classifier> getDefinition();

    List<? extends Usage> getDirectedUsage();

    Boolean getIsReference();

    Boolean getIsVariation();

    Boolean getMayTimeVary();

    List<? extends ActionUsage> getNestedAction();

    List<? extends AllocationUsage> getNestedAllocation();

    List<? extends AnalysisCaseUsage> getNestedAnalysisCase();

    List<? extends AttributeUsage> getNestedAttribute();

    List<? extends CalculationUsage> getNestedCalculation();

    List<? extends CaseUsage> getNestedCase();

    Collection<? extends ConcernUsage> getNestedConcern();

    List<? extends ConnectorAsUsage> getNestedConnection();

    List<? extends ConstraintUsage> getNestedConstraint();

    List<? extends EnumerationUsage> getNestedEnumeration();

    Collection<? extends FlowUsage> getNestedFlow();

    List<? extends InterfaceUsage> getNestedInterface();

    List<? extends ItemUsage> getNestedItem();

    List<? extends MetadataUsage> getNestedMetadata();

    List<? extends OccurrenceUsage> getNestedOccurrence();

    List<? extends PartUsage> getNestedPart();

    List<? extends PortUsage> getNestedPort();

    List<? extends ReferenceUsage> getNestedReference();

    List<? extends RenderingUsage> getNestedRendering();

    List<? extends RequirementUsage> getNestedRequirement();

    List<? extends StateUsage> getNestedState();

    Collection<? extends TransitionUsage> getNestedTransition();

    List<? extends Usage> getNestedUsage();

    List<? extends UseCaseUsage> getNestedUseCase();

    List<? extends VerificationCaseUsage> getNestedVerificationCase();

    List<? extends ViewUsage> getNestedView();

    List<? extends ViewpointUsage> getNestedViewpoint();

    Definition getOwningDefinition();

    Usage getOwningUsage();

    List<? extends Usage> getUsage();

    Collection<? extends Usage> getVariant();

    Collection<? extends VariantMembership> getVariantMembership();
}