// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package org.omg.sysml.metamodel;

import java.util.Collection;
import java.util.List;
import java.util.Set;

public interface ViewDefinition extends PartDefinition, SysMLType {
    List<? extends ViewpointUsage> getSatisfiedViewpoint();

    List<? extends ViewUsage> getView();

    List<? extends Expression> getViewCondition();

    RenderingUsage getViewRendering();
}