INSERT INTO models (identifier,description,name) VALUES (b087f8d0-b5d6-11e8-8e53-dbf8bfefb057,'SysML v2 model with part interconnections for Vehicle.','Parts Interconnection Model');
INSERT INTO models (identifier,description,name) VALUES (38adb230-c280-11e8-9b50-31ef94e7c134,'Functional Allocation Validation Case','Functional Allocation');
INSERT INTO models (identifier,description,name) VALUES (65df24d2-b52e-11e8-96f8-529269fb1459,'This is a sandbox SysML v2 model.','Sandbox model');
INSERT INTO models (identifier,description,name) VALUES (55b2d4b0-b5c8-11e8-8e53-dbf8bfefb057,'SysML v2 model with part trees of Vehicles.','Vehicle Parts Tree');
