@AnyMetaDefs(value = {
        @AnyMetaDef(name = "ReturnParameterMembershipMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "ReturnParameterMembership", targetEntity = ReturnParameterMembershipImpl.class),
                }),
        @AnyMetaDef(name = "ItemFlowMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "ItemFlow", targetEntity = ItemFlowImpl.class),
                        @MetaValue(value = "SuccessionItemFlow", targetEntity = SuccessionItemFlowImpl.class),
                }),
        @AnyMetaDef(name = "FeatureTypingMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "FeatureTyping", targetEntity = FeatureTypingImpl.class),
                }),
        @AnyMetaDef(name = "ImportMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "Import", targetEntity = ImportImpl.class),
                }),
        @AnyMetaDef(name = "LiteralStringMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "LiteralString", targetEntity = LiteralStringImpl.class),
                }),
        @AnyMetaDef(name = "FeatureMembershipMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "ReturnParameterMembership", targetEntity = ReturnParameterMembershipImpl.class),
                        @MetaValue(value = "FeatureMembership", targetEntity = FeatureMembershipImpl.class),
                        @MetaValue(value = "ParameterMembership", targetEntity = ParameterMembershipImpl.class),
                        @MetaValue(value = "EndFeatureMembership", targetEntity = EndFeatureMembershipImpl.class),
                }),
        @AnyMetaDef(name = "OrderedFeatureMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "OrderedFeature", targetEntity = OrderedFeatureImpl.class),
                }),
        @AnyMetaDef(name = "QueryPathExpressionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "QueryPathExpression", targetEntity = QueryPathExpressionImpl.class),
                }),
        @AnyMetaDef(name = "GeneralizationMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "FeatureTyping", targetEntity = FeatureTypingImpl.class),
                        @MetaValue(value = "Generalization", targetEntity = GeneralizationImpl.class),
                        @MetaValue(value = "Subsetting", targetEntity = SubsettingImpl.class),
                        @MetaValue(value = "Superclassing", targetEntity = SuperclassingImpl.class),
                        @MetaValue(value = "Redefinition", targetEntity = RedefinitionImpl.class),
                }),
        @AnyMetaDef(name = "FeatureMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "ItemFlow", targetEntity = ItemFlowImpl.class),
                        @MetaValue(value = "LiteralString", targetEntity = LiteralStringImpl.class),
                        @MetaValue(value = "OrderedFeature", targetEntity = OrderedFeatureImpl.class),
                        @MetaValue(value = "QueryPathExpression", targetEntity = QueryPathExpressionImpl.class),
                        @MetaValue(value = "Feature", targetEntity = FeatureImpl.class),
                        @MetaValue(value = "SourceEnd", targetEntity = SourceEndImpl.class),
                        @MetaValue(value = "LiteralBoolean", targetEntity = LiteralBooleanImpl.class),
                        @MetaValue(value = "InstanceCreationExpression", targetEntity = InstanceCreationExpressionImpl.class),
                        @MetaValue(value = "LiteralExpression", targetEntity = LiteralExpressionImpl.class),
                        @MetaValue(value = "ItemFlowFeature", targetEntity = ItemFlowFeatureImpl.class),
                        @MetaValue(value = "SuccessionItemFlow", targetEntity = SuccessionItemFlowImpl.class),
                        @MetaValue(value = "NullExpression", targetEntity = NullExpressionImpl.class),
                        @MetaValue(value = "FeatureReferenceExpression", targetEntity = FeatureReferenceExpressionImpl.class),
                        @MetaValue(value = "StructuredFeature", targetEntity = StructuredFeatureImpl.class),
                        @MetaValue(value = "TargetEnd", targetEntity = TargetEndImpl.class),
                        @MetaValue(value = "Connector", targetEntity = ConnectorImpl.class),
                        @MetaValue(value = "QueryQualifierExpression", targetEntity = QueryQualifierExpressionImpl.class),
                        @MetaValue(value = "BindingConnector", targetEntity = BindingConnectorImpl.class),
                        @MetaValue(value = "InvocationExpression", targetEntity = InvocationExpressionImpl.class),
                        @MetaValue(value = "Step", targetEntity = StepImpl.class),
                        @MetaValue(value = "LiteralReal", targetEntity = LiteralRealImpl.class),
                        @MetaValue(value = "Succession", targetEntity = SuccessionImpl.class),
                        @MetaValue(value = "OperatorExpression", targetEntity = OperatorExpressionImpl.class),
                        @MetaValue(value = "ItemFlowEnd", targetEntity = ItemFlowEndImpl.class),
                        @MetaValue(value = "BlockExpression", targetEntity = BlockExpressionImpl.class),
                        @MetaValue(value = "LiteralInteger", targetEntity = LiteralIntegerImpl.class),
                        @MetaValue(value = "LiteralUnbounded", targetEntity = LiteralUnboundedImpl.class),
                        @MetaValue(value = "Expression", targetEntity = ExpressionImpl.class),
                        @MetaValue(value = "SequenceConstructionExpression", targetEntity = SequenceConstructionExpressionImpl.class),
                        @MetaValue(value = "Parameter", targetEntity = ParameterImpl.class),
                        @MetaValue(value = "ItemFeature", targetEntity = ItemFeatureImpl.class),
                        @MetaValue(value = "QueryPathStepExpression", targetEntity = QueryPathStepExpressionImpl.class),
                }),
        @AnyMetaDef(name = "PredicateMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "Predicate", targetEntity = PredicateImpl.class),
                }),
        @AnyMetaDef(name = "SourceEndMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "SourceEnd", targetEntity = SourceEndImpl.class),
                }),
        @AnyMetaDef(name = "SubsettingMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "Subsetting", targetEntity = SubsettingImpl.class),
                        @MetaValue(value = "Redefinition", targetEntity = RedefinitionImpl.class),
                }),
        @AnyMetaDef(name = "MembershipMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "ReturnParameterMembership", targetEntity = ReturnParameterMembershipImpl.class),
                        @MetaValue(value = "FeatureMembership", targetEntity = FeatureMembershipImpl.class),
                        @MetaValue(value = "Membership", targetEntity = MembershipImpl.class),
                        @MetaValue(value = "ParameterMembership", targetEntity = ParameterMembershipImpl.class),
                        @MetaValue(value = "EndFeatureMembership", targetEntity = EndFeatureMembershipImpl.class),
                }),
        @AnyMetaDef(name = "MofObjectMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "FeatureTyping", targetEntity = FeatureTypingImpl.class),
                        @MetaValue(value = "ItemFlow", targetEntity = ItemFlowImpl.class),
                        @MetaValue(value = "ReturnParameterMembership", targetEntity = ReturnParameterMembershipImpl.class),
                        @MetaValue(value = "Import", targetEntity = ImportImpl.class),
                        @MetaValue(value = "LiteralString", targetEntity = LiteralStringImpl.class),
                        @MetaValue(value = "FeatureMembership", targetEntity = FeatureMembershipImpl.class),
                        @MetaValue(value = "OrderedFeature", targetEntity = OrderedFeatureImpl.class),
                        @MetaValue(value = "QueryPathExpression", targetEntity = QueryPathExpressionImpl.class),
                        @MetaValue(value = "Generalization", targetEntity = GeneralizationImpl.class),
                        @MetaValue(value = "Feature", targetEntity = FeatureImpl.class),
                        @MetaValue(value = "Predicate", targetEntity = PredicateImpl.class),
                        @MetaValue(value = "SourceEnd", targetEntity = SourceEndImpl.class),
                        @MetaValue(value = "Subsetting", targetEntity = SubsettingImpl.class),
                        @MetaValue(value = "Membership", targetEntity = MembershipImpl.class),
                        @MetaValue(value = "Behavior", targetEntity = BehaviorImpl.class),
                        @MetaValue(value = "LiteralBoolean", targetEntity = LiteralBooleanImpl.class),
                        @MetaValue(value = "InstanceCreationExpression", targetEntity = InstanceCreationExpressionImpl.class),
                        @MetaValue(value = "Interaction", targetEntity = InteractionImpl.class),
                        @MetaValue(value = "LiteralExpression", targetEntity = LiteralExpressionImpl.class),
                        @MetaValue(value = "ParameterMembership", targetEntity = ParameterMembershipImpl.class),
                        @MetaValue(value = "ItemFlowFeature", targetEntity = ItemFlowFeatureImpl.class),
                        @MetaValue(value = "SuccessionItemFlow", targetEntity = SuccessionItemFlowImpl.class),
                        @MetaValue(value = "OFSuccession", targetEntity = OFSuccessionImpl.class),
                        @MetaValue(value = "NullExpression", targetEntity = NullExpressionImpl.class),
                        @MetaValue(value = "FeatureReferenceExpression", targetEntity = FeatureReferenceExpressionImpl.class),
                        @MetaValue(value = "StructuredFeature", targetEntity = StructuredFeatureImpl.class),
                        @MetaValue(value = "Superclassing", targetEntity = SuperclassingImpl.class),
                        @MetaValue(value = "Class", targetEntity = ClassImpl.class),
                        @MetaValue(value = "Package", targetEntity = PackageImpl.class),
                        @MetaValue(value = "TargetEnd", targetEntity = TargetEndImpl.class),
                        @MetaValue(value = "Connector", targetEntity = ConnectorImpl.class),
                        @MetaValue(value = "Ownership", targetEntity = OwnershipImpl.class),
                        @MetaValue(value = "QueryQualifierExpression", targetEntity = QueryQualifierExpressionImpl.class),
                        @MetaValue(value = "BindingConnector", targetEntity = BindingConnectorImpl.class),
                        @MetaValue(value = "Element", targetEntity = ElementImpl.class),
                        @MetaValue(value = "Classifier", targetEntity = ClassifierImpl.class),
                        @MetaValue(value = "InvocationExpression", targetEntity = InvocationExpressionImpl.class),
                        @MetaValue(value = "Step", targetEntity = StepImpl.class),
                        @MetaValue(value = "Redefinition", targetEntity = RedefinitionImpl.class),
                        @MetaValue(value = "LiteralReal", targetEntity = LiteralRealImpl.class),
                        @MetaValue(value = "Function", targetEntity = FunctionImpl.class),
                        @MetaValue(value = "Succession", targetEntity = SuccessionImpl.class),
                        @MetaValue(value = "Association", targetEntity = AssociationImpl.class),
                        @MetaValue(value = "Multiplicity", targetEntity = MultiplicityImpl.class),
                        @MetaValue(value = "AtomicInteraction", targetEntity = AtomicInteractionImpl.class),
                        @MetaValue(value = "OperatorExpression", targetEntity = OperatorExpressionImpl.class),
                        @MetaValue(value = "DataType", targetEntity = DataTypeImpl.class),
                        @MetaValue(value = "Comment", targetEntity = CommentImpl.class),
                        @MetaValue(value = "EndFeatureMembership", targetEntity = EndFeatureMembershipImpl.class),
                        @MetaValue(value = "ItemFlowEnd", targetEntity = ItemFlowEndImpl.class),
                        @MetaValue(value = "BlockExpression", targetEntity = BlockExpressionImpl.class),
                        @MetaValue(value = "FeatureValue", targetEntity = FeatureValueImpl.class),
                        @MetaValue(value = "Annotation", targetEntity = AnnotationImpl.class),
                        @MetaValue(value = "LiteralInteger", targetEntity = LiteralIntegerImpl.class),
                        @MetaValue(value = "LiteralUnbounded", targetEntity = LiteralUnboundedImpl.class),
                        @MetaValue(value = "Type", targetEntity = TypeImpl.class),
                        @MetaValue(value = "Expression", targetEntity = ExpressionImpl.class),
                        @MetaValue(value = "SequenceConstructionExpression", targetEntity = SequenceConstructionExpressionImpl.class),
                        @MetaValue(value = "Relationship", targetEntity = RelationshipImpl.class),
                        @MetaValue(value = "Parameter", targetEntity = ParameterImpl.class),
                        @MetaValue(value = "ItemFeature", targetEntity = ItemFeatureImpl.class),
                        @MetaValue(value = "QueryPathStepExpression", targetEntity = QueryPathStepExpressionImpl.class),
                }),
        @AnyMetaDef(name = "BehaviorMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "Predicate", targetEntity = PredicateImpl.class),
                        @MetaValue(value = "Behavior", targetEntity = BehaviorImpl.class),
                        @MetaValue(value = "Interaction", targetEntity = InteractionImpl.class),
                        @MetaValue(value = "Function", targetEntity = FunctionImpl.class),
                }),
        @AnyMetaDef(name = "LiteralBooleanMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "LiteralBoolean", targetEntity = LiteralBooleanImpl.class),
                }),
        @AnyMetaDef(name = "InstanceCreationExpressionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "InstanceCreationExpression", targetEntity = InstanceCreationExpressionImpl.class),
                }),
        @AnyMetaDef(name = "InteractionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "Interaction", targetEntity = InteractionImpl.class),
                }),
        @AnyMetaDef(name = "LiteralExpressionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "LiteralString", targetEntity = LiteralStringImpl.class),
                        @MetaValue(value = "LiteralBoolean", targetEntity = LiteralBooleanImpl.class),
                        @MetaValue(value = "LiteralExpression", targetEntity = LiteralExpressionImpl.class),
                        @MetaValue(value = "LiteralReal", targetEntity = LiteralRealImpl.class),
                        @MetaValue(value = "LiteralInteger", targetEntity = LiteralIntegerImpl.class),
                        @MetaValue(value = "LiteralUnbounded", targetEntity = LiteralUnboundedImpl.class),
                }),
        @AnyMetaDef(name = "ParameterMembershipMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "ReturnParameterMembership", targetEntity = ReturnParameterMembershipImpl.class),
                        @MetaValue(value = "ParameterMembership", targetEntity = ParameterMembershipImpl.class),
                }),
        @AnyMetaDef(name = "ItemFlowFeatureMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "ItemFlowFeature", targetEntity = ItemFlowFeatureImpl.class),
                }),
        @AnyMetaDef(name = "SuccessionItemFlowMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "SuccessionItemFlow", targetEntity = SuccessionItemFlowImpl.class),
                }),
        @AnyMetaDef(name = "OFSuccessionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "OFSuccession", targetEntity = OFSuccessionImpl.class),
                }),
        @AnyMetaDef(name = "NullExpressionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "NullExpression", targetEntity = NullExpressionImpl.class),
                }),
        @AnyMetaDef(name = "SuperclassingMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "Superclassing", targetEntity = SuperclassingImpl.class),
                }),
        @AnyMetaDef(name = "FeatureReferenceExpressionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "QueryPathExpression", targetEntity = QueryPathExpressionImpl.class),
                        @MetaValue(value = "FeatureReferenceExpression", targetEntity = FeatureReferenceExpressionImpl.class),
                }),
        @AnyMetaDef(name = "StructuredFeatureMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "OrderedFeature", targetEntity = OrderedFeatureImpl.class),
                        @MetaValue(value = "StructuredFeature", targetEntity = StructuredFeatureImpl.class),
                }),
        @AnyMetaDef(name = "ClassMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "Interaction", targetEntity = InteractionImpl.class),
                        @MetaValue(value = "Class", targetEntity = ClassImpl.class),
                        @MetaValue(value = "Association", targetEntity = AssociationImpl.class),
                }),
        @AnyMetaDef(name = "PackageMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "ItemFlow", targetEntity = ItemFlowImpl.class),
                        @MetaValue(value = "LiteralString", targetEntity = LiteralStringImpl.class),
                        @MetaValue(value = "OrderedFeature", targetEntity = OrderedFeatureImpl.class),
                        @MetaValue(value = "QueryPathExpression", targetEntity = QueryPathExpressionImpl.class),
                        @MetaValue(value = "Feature", targetEntity = FeatureImpl.class),
                        @MetaValue(value = "Predicate", targetEntity = PredicateImpl.class),
                        @MetaValue(value = "SourceEnd", targetEntity = SourceEndImpl.class),
                        @MetaValue(value = "Behavior", targetEntity = BehaviorImpl.class),
                        @MetaValue(value = "LiteralBoolean", targetEntity = LiteralBooleanImpl.class),
                        @MetaValue(value = "InstanceCreationExpression", targetEntity = InstanceCreationExpressionImpl.class),
                        @MetaValue(value = "Interaction", targetEntity = InteractionImpl.class),
                        @MetaValue(value = "LiteralExpression", targetEntity = LiteralExpressionImpl.class),
                        @MetaValue(value = "ItemFlowFeature", targetEntity = ItemFlowFeatureImpl.class),
                        @MetaValue(value = "SuccessionItemFlow", targetEntity = SuccessionItemFlowImpl.class),
                        @MetaValue(value = "NullExpression", targetEntity = NullExpressionImpl.class),
                        @MetaValue(value = "FeatureReferenceExpression", targetEntity = FeatureReferenceExpressionImpl.class),
                        @MetaValue(value = "StructuredFeature", targetEntity = StructuredFeatureImpl.class),
                        @MetaValue(value = "Class", targetEntity = ClassImpl.class),
                        @MetaValue(value = "Package", targetEntity = PackageImpl.class),
                        @MetaValue(value = "TargetEnd", targetEntity = TargetEndImpl.class),
                        @MetaValue(value = "Connector", targetEntity = ConnectorImpl.class),
                        @MetaValue(value = "QueryQualifierExpression", targetEntity = QueryQualifierExpressionImpl.class),
                        @MetaValue(value = "BindingConnector", targetEntity = BindingConnectorImpl.class),
                        @MetaValue(value = "Classifier", targetEntity = ClassifierImpl.class),
                        @MetaValue(value = "InvocationExpression", targetEntity = InvocationExpressionImpl.class),
                        @MetaValue(value = "Step", targetEntity = StepImpl.class),
                        @MetaValue(value = "LiteralReal", targetEntity = LiteralRealImpl.class),
                        @MetaValue(value = "Function", targetEntity = FunctionImpl.class),
                        @MetaValue(value = "Succession", targetEntity = SuccessionImpl.class),
                        @MetaValue(value = "Association", targetEntity = AssociationImpl.class),
                        @MetaValue(value = "OperatorExpression", targetEntity = OperatorExpressionImpl.class),
                        @MetaValue(value = "DataType", targetEntity = DataTypeImpl.class),
                        @MetaValue(value = "ItemFlowEnd", targetEntity = ItemFlowEndImpl.class),
                        @MetaValue(value = "BlockExpression", targetEntity = BlockExpressionImpl.class),
                        @MetaValue(value = "LiteralInteger", targetEntity = LiteralIntegerImpl.class),
                        @MetaValue(value = "LiteralUnbounded", targetEntity = LiteralUnboundedImpl.class),
                        @MetaValue(value = "Type", targetEntity = TypeImpl.class),
                        @MetaValue(value = "Expression", targetEntity = ExpressionImpl.class),
                        @MetaValue(value = "SequenceConstructionExpression", targetEntity = SequenceConstructionExpressionImpl.class),
                        @MetaValue(value = "Parameter", targetEntity = ParameterImpl.class),
                        @MetaValue(value = "ItemFeature", targetEntity = ItemFeatureImpl.class),
                        @MetaValue(value = "QueryPathStepExpression", targetEntity = QueryPathStepExpressionImpl.class),
                }),
        @AnyMetaDef(name = "TargetEndMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "TargetEnd", targetEntity = TargetEndImpl.class),
                }),
        @AnyMetaDef(name = "ConnectorMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "ItemFlow", targetEntity = ItemFlowImpl.class),
                        @MetaValue(value = "SuccessionItemFlow", targetEntity = SuccessionItemFlowImpl.class),
                        @MetaValue(value = "Connector", targetEntity = ConnectorImpl.class),
                        @MetaValue(value = "BindingConnector", targetEntity = BindingConnectorImpl.class),
                        @MetaValue(value = "Succession", targetEntity = SuccessionImpl.class),
                }),
        @AnyMetaDef(name = "OwnershipMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "Ownership", targetEntity = OwnershipImpl.class),
                }),
        @AnyMetaDef(name = "QueryQualifierExpressionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "QueryQualifierExpression", targetEntity = QueryQualifierExpressionImpl.class),
                }),
        @AnyMetaDef(name = "BindingConnectorMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "BindingConnector", targetEntity = BindingConnectorImpl.class),
                }),
        @AnyMetaDef(name = "ElementMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "FeatureTyping", targetEntity = FeatureTypingImpl.class),
                        @MetaValue(value = "ItemFlow", targetEntity = ItemFlowImpl.class),
                        @MetaValue(value = "ReturnParameterMembership", targetEntity = ReturnParameterMembershipImpl.class),
                        @MetaValue(value = "Import", targetEntity = ImportImpl.class),
                        @MetaValue(value = "LiteralString", targetEntity = LiteralStringImpl.class),
                        @MetaValue(value = "FeatureMembership", targetEntity = FeatureMembershipImpl.class),
                        @MetaValue(value = "OrderedFeature", targetEntity = OrderedFeatureImpl.class),
                        @MetaValue(value = "QueryPathExpression", targetEntity = QueryPathExpressionImpl.class),
                        @MetaValue(value = "Generalization", targetEntity = GeneralizationImpl.class),
                        @MetaValue(value = "Feature", targetEntity = FeatureImpl.class),
                        @MetaValue(value = "Predicate", targetEntity = PredicateImpl.class),
                        @MetaValue(value = "SourceEnd", targetEntity = SourceEndImpl.class),
                        @MetaValue(value = "Subsetting", targetEntity = SubsettingImpl.class),
                        @MetaValue(value = "Membership", targetEntity = MembershipImpl.class),
                        @MetaValue(value = "Behavior", targetEntity = BehaviorImpl.class),
                        @MetaValue(value = "LiteralBoolean", targetEntity = LiteralBooleanImpl.class),
                        @MetaValue(value = "InstanceCreationExpression", targetEntity = InstanceCreationExpressionImpl.class),
                        @MetaValue(value = "Interaction", targetEntity = InteractionImpl.class),
                        @MetaValue(value = "LiteralExpression", targetEntity = LiteralExpressionImpl.class),
                        @MetaValue(value = "ParameterMembership", targetEntity = ParameterMembershipImpl.class),
                        @MetaValue(value = "ItemFlowFeature", targetEntity = ItemFlowFeatureImpl.class),
                        @MetaValue(value = "SuccessionItemFlow", targetEntity = SuccessionItemFlowImpl.class),
                        @MetaValue(value = "NullExpression", targetEntity = NullExpressionImpl.class),
                        @MetaValue(value = "FeatureReferenceExpression", targetEntity = FeatureReferenceExpressionImpl.class),
                        @MetaValue(value = "StructuredFeature", targetEntity = StructuredFeatureImpl.class),
                        @MetaValue(value = "Superclassing", targetEntity = SuperclassingImpl.class),
                        @MetaValue(value = "Class", targetEntity = ClassImpl.class),
                        @MetaValue(value = "Package", targetEntity = PackageImpl.class),
                        @MetaValue(value = "TargetEnd", targetEntity = TargetEndImpl.class),
                        @MetaValue(value = "Connector", targetEntity = ConnectorImpl.class),
                        @MetaValue(value = "Ownership", targetEntity = OwnershipImpl.class),
                        @MetaValue(value = "QueryQualifierExpression", targetEntity = QueryQualifierExpressionImpl.class),
                        @MetaValue(value = "BindingConnector", targetEntity = BindingConnectorImpl.class),
                        @MetaValue(value = "Element", targetEntity = ElementImpl.class),
                        @MetaValue(value = "Classifier", targetEntity = ClassifierImpl.class),
                        @MetaValue(value = "InvocationExpression", targetEntity = InvocationExpressionImpl.class),
                        @MetaValue(value = "Step", targetEntity = StepImpl.class),
                        @MetaValue(value = "Redefinition", targetEntity = RedefinitionImpl.class),
                        @MetaValue(value = "LiteralReal", targetEntity = LiteralRealImpl.class),
                        @MetaValue(value = "Function", targetEntity = FunctionImpl.class),
                        @MetaValue(value = "Succession", targetEntity = SuccessionImpl.class),
                        @MetaValue(value = "Association", targetEntity = AssociationImpl.class),
                        @MetaValue(value = "Multiplicity", targetEntity = MultiplicityImpl.class),
                        @MetaValue(value = "OperatorExpression", targetEntity = OperatorExpressionImpl.class),
                        @MetaValue(value = "DataType", targetEntity = DataTypeImpl.class),
                        @MetaValue(value = "Comment", targetEntity = CommentImpl.class),
                        @MetaValue(value = "EndFeatureMembership", targetEntity = EndFeatureMembershipImpl.class),
                        @MetaValue(value = "ItemFlowEnd", targetEntity = ItemFlowEndImpl.class),
                        @MetaValue(value = "BlockExpression", targetEntity = BlockExpressionImpl.class),
                        @MetaValue(value = "FeatureValue", targetEntity = FeatureValueImpl.class),
                        @MetaValue(value = "Annotation", targetEntity = AnnotationImpl.class),
                        @MetaValue(value = "LiteralInteger", targetEntity = LiteralIntegerImpl.class),
                        @MetaValue(value = "LiteralUnbounded", targetEntity = LiteralUnboundedImpl.class),
                        @MetaValue(value = "Type", targetEntity = TypeImpl.class),
                        @MetaValue(value = "Expression", targetEntity = ExpressionImpl.class),
                        @MetaValue(value = "SequenceConstructionExpression", targetEntity = SequenceConstructionExpressionImpl.class),
                        @MetaValue(value = "Relationship", targetEntity = RelationshipImpl.class),
                        @MetaValue(value = "Parameter", targetEntity = ParameterImpl.class),
                        @MetaValue(value = "ItemFeature", targetEntity = ItemFeatureImpl.class),
                        @MetaValue(value = "QueryPathStepExpression", targetEntity = QueryPathStepExpressionImpl.class),
                }),
        @AnyMetaDef(name = "InvocationExpressionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "InstanceCreationExpression", targetEntity = InstanceCreationExpressionImpl.class),
                        @MetaValue(value = "QueryQualifierExpression", targetEntity = QueryQualifierExpressionImpl.class),
                        @MetaValue(value = "InvocationExpression", targetEntity = InvocationExpressionImpl.class),
                        @MetaValue(value = "OperatorExpression", targetEntity = OperatorExpressionImpl.class),
                        @MetaValue(value = "QueryPathStepExpression", targetEntity = QueryPathStepExpressionImpl.class),
                }),
        @AnyMetaDef(name = "ClassifierMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "Predicate", targetEntity = PredicateImpl.class),
                        @MetaValue(value = "Behavior", targetEntity = BehaviorImpl.class),
                        @MetaValue(value = "Interaction", targetEntity = InteractionImpl.class),
                        @MetaValue(value = "Class", targetEntity = ClassImpl.class),
                        @MetaValue(value = "Classifier", targetEntity = ClassifierImpl.class),
                        @MetaValue(value = "Function", targetEntity = FunctionImpl.class),
                        @MetaValue(value = "Association", targetEntity = AssociationImpl.class),
                        @MetaValue(value = "DataType", targetEntity = DataTypeImpl.class),
                }),
        @AnyMetaDef(name = "StepMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "ItemFlow", targetEntity = ItemFlowImpl.class),
                        @MetaValue(value = "LiteralString", targetEntity = LiteralStringImpl.class),
                        @MetaValue(value = "QueryPathExpression", targetEntity = QueryPathExpressionImpl.class),
                        @MetaValue(value = "LiteralBoolean", targetEntity = LiteralBooleanImpl.class),
                        @MetaValue(value = "InstanceCreationExpression", targetEntity = InstanceCreationExpressionImpl.class),
                        @MetaValue(value = "LiteralExpression", targetEntity = LiteralExpressionImpl.class),
                        @MetaValue(value = "SuccessionItemFlow", targetEntity = SuccessionItemFlowImpl.class),
                        @MetaValue(value = "NullExpression", targetEntity = NullExpressionImpl.class),
                        @MetaValue(value = "FeatureReferenceExpression", targetEntity = FeatureReferenceExpressionImpl.class),
                        @MetaValue(value = "QueryQualifierExpression", targetEntity = QueryQualifierExpressionImpl.class),
                        @MetaValue(value = "InvocationExpression", targetEntity = InvocationExpressionImpl.class),
                        @MetaValue(value = "Step", targetEntity = StepImpl.class),
                        @MetaValue(value = "LiteralReal", targetEntity = LiteralRealImpl.class),
                        @MetaValue(value = "OperatorExpression", targetEntity = OperatorExpressionImpl.class),
                        @MetaValue(value = "BlockExpression", targetEntity = BlockExpressionImpl.class),
                        @MetaValue(value = "LiteralInteger", targetEntity = LiteralIntegerImpl.class),
                        @MetaValue(value = "LiteralUnbounded", targetEntity = LiteralUnboundedImpl.class),
                        @MetaValue(value = "Expression", targetEntity = ExpressionImpl.class),
                        @MetaValue(value = "SequenceConstructionExpression", targetEntity = SequenceConstructionExpressionImpl.class),
                        @MetaValue(value = "QueryPathStepExpression", targetEntity = QueryPathStepExpressionImpl.class),
                }),
        @AnyMetaDef(name = "RedefinitionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "Redefinition", targetEntity = RedefinitionImpl.class),
                }),
        @AnyMetaDef(name = "LiteralRealMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "LiteralReal", targetEntity = LiteralRealImpl.class),
                }),
        @AnyMetaDef(name = "FunctionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "Predicate", targetEntity = PredicateImpl.class),
                        @MetaValue(value = "Function", targetEntity = FunctionImpl.class),
                }),
        @AnyMetaDef(name = "SuccessionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "SuccessionItemFlow", targetEntity = SuccessionItemFlowImpl.class),
                        @MetaValue(value = "Succession", targetEntity = SuccessionImpl.class),
                }),
        @AnyMetaDef(name = "AssociationMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "Interaction", targetEntity = InteractionImpl.class),
                        @MetaValue(value = "Association", targetEntity = AssociationImpl.class),
                }),
        @AnyMetaDef(name = "MultiplicityMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "Multiplicity", targetEntity = MultiplicityImpl.class),
                }),
        @AnyMetaDef(name = "AtomicInteractionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "AtomicInteraction", targetEntity = AtomicInteractionImpl.class),
                }),
        @AnyMetaDef(name = "OperatorExpressionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "QueryQualifierExpression", targetEntity = QueryQualifierExpressionImpl.class),
                        @MetaValue(value = "OperatorExpression", targetEntity = OperatorExpressionImpl.class),
                        @MetaValue(value = "QueryPathStepExpression", targetEntity = QueryPathStepExpressionImpl.class),
                }),
        @AnyMetaDef(name = "DataTypeMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "DataType", targetEntity = DataTypeImpl.class),
                }),
        @AnyMetaDef(name = "CommentMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "Comment", targetEntity = CommentImpl.class),
                }),
        @AnyMetaDef(name = "ItemFlowEndMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "ItemFlowEnd", targetEntity = ItemFlowEndImpl.class),
                }),
        @AnyMetaDef(name = "EndFeatureMembershipMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "EndFeatureMembership", targetEntity = EndFeatureMembershipImpl.class),
                }),
        @AnyMetaDef(name = "BlockExpressionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "BlockExpression", targetEntity = BlockExpressionImpl.class),
                }),
        @AnyMetaDef(name = "FeatureValueMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "FeatureValue", targetEntity = FeatureValueImpl.class),
                }),
        @AnyMetaDef(name = "AnnotationMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "Annotation", targetEntity = AnnotationImpl.class),
                }),
        @AnyMetaDef(name = "LiteralIntegerMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "LiteralInteger", targetEntity = LiteralIntegerImpl.class),
                }),
        @AnyMetaDef(name = "LiteralUnboundedMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "LiteralUnbounded", targetEntity = LiteralUnboundedImpl.class),
                }),
        @AnyMetaDef(name = "TypeMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "ItemFlow", targetEntity = ItemFlowImpl.class),
                        @MetaValue(value = "LiteralString", targetEntity = LiteralStringImpl.class),
                        @MetaValue(value = "OrderedFeature", targetEntity = OrderedFeatureImpl.class),
                        @MetaValue(value = "QueryPathExpression", targetEntity = QueryPathExpressionImpl.class),
                        @MetaValue(value = "Feature", targetEntity = FeatureImpl.class),
                        @MetaValue(value = "Predicate", targetEntity = PredicateImpl.class),
                        @MetaValue(value = "SourceEnd", targetEntity = SourceEndImpl.class),
                        @MetaValue(value = "Behavior", targetEntity = BehaviorImpl.class),
                        @MetaValue(value = "LiteralBoolean", targetEntity = LiteralBooleanImpl.class),
                        @MetaValue(value = "InstanceCreationExpression", targetEntity = InstanceCreationExpressionImpl.class),
                        @MetaValue(value = "Interaction", targetEntity = InteractionImpl.class),
                        @MetaValue(value = "LiteralExpression", targetEntity = LiteralExpressionImpl.class),
                        @MetaValue(value = "ItemFlowFeature", targetEntity = ItemFlowFeatureImpl.class),
                        @MetaValue(value = "SuccessionItemFlow", targetEntity = SuccessionItemFlowImpl.class),
                        @MetaValue(value = "NullExpression", targetEntity = NullExpressionImpl.class),
                        @MetaValue(value = "FeatureReferenceExpression", targetEntity = FeatureReferenceExpressionImpl.class),
                        @MetaValue(value = "StructuredFeature", targetEntity = StructuredFeatureImpl.class),
                        @MetaValue(value = "Class", targetEntity = ClassImpl.class),
                        @MetaValue(value = "TargetEnd", targetEntity = TargetEndImpl.class),
                        @MetaValue(value = "Connector", targetEntity = ConnectorImpl.class),
                        @MetaValue(value = "QueryQualifierExpression", targetEntity = QueryQualifierExpressionImpl.class),
                        @MetaValue(value = "BindingConnector", targetEntity = BindingConnectorImpl.class),
                        @MetaValue(value = "Classifier", targetEntity = ClassifierImpl.class),
                        @MetaValue(value = "InvocationExpression", targetEntity = InvocationExpressionImpl.class),
                        @MetaValue(value = "Step", targetEntity = StepImpl.class),
                        @MetaValue(value = "LiteralReal", targetEntity = LiteralRealImpl.class),
                        @MetaValue(value = "Function", targetEntity = FunctionImpl.class),
                        @MetaValue(value = "Succession", targetEntity = SuccessionImpl.class),
                        @MetaValue(value = "Association", targetEntity = AssociationImpl.class),
                        @MetaValue(value = "OperatorExpression", targetEntity = OperatorExpressionImpl.class),
                        @MetaValue(value = "DataType", targetEntity = DataTypeImpl.class),
                        @MetaValue(value = "ItemFlowEnd", targetEntity = ItemFlowEndImpl.class),
                        @MetaValue(value = "BlockExpression", targetEntity = BlockExpressionImpl.class),
                        @MetaValue(value = "LiteralInteger", targetEntity = LiteralIntegerImpl.class),
                        @MetaValue(value = "LiteralUnbounded", targetEntity = LiteralUnboundedImpl.class),
                        @MetaValue(value = "Type", targetEntity = TypeImpl.class),
                        @MetaValue(value = "Expression", targetEntity = ExpressionImpl.class),
                        @MetaValue(value = "SequenceConstructionExpression", targetEntity = SequenceConstructionExpressionImpl.class),
                        @MetaValue(value = "Parameter", targetEntity = ParameterImpl.class),
                        @MetaValue(value = "ItemFeature", targetEntity = ItemFeatureImpl.class),
                        @MetaValue(value = "QueryPathStepExpression", targetEntity = QueryPathStepExpressionImpl.class),
                }),
        @AnyMetaDef(name = "ExpressionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "LiteralString", targetEntity = LiteralStringImpl.class),
                        @MetaValue(value = "QueryPathExpression", targetEntity = QueryPathExpressionImpl.class),
                        @MetaValue(value = "LiteralBoolean", targetEntity = LiteralBooleanImpl.class),
                        @MetaValue(value = "InstanceCreationExpression", targetEntity = InstanceCreationExpressionImpl.class),
                        @MetaValue(value = "LiteralExpression", targetEntity = LiteralExpressionImpl.class),
                        @MetaValue(value = "NullExpression", targetEntity = NullExpressionImpl.class),
                        @MetaValue(value = "FeatureReferenceExpression", targetEntity = FeatureReferenceExpressionImpl.class),
                        @MetaValue(value = "QueryQualifierExpression", targetEntity = QueryQualifierExpressionImpl.class),
                        @MetaValue(value = "InvocationExpression", targetEntity = InvocationExpressionImpl.class),
                        @MetaValue(value = "LiteralReal", targetEntity = LiteralRealImpl.class),
                        @MetaValue(value = "OperatorExpression", targetEntity = OperatorExpressionImpl.class),
                        @MetaValue(value = "BlockExpression", targetEntity = BlockExpressionImpl.class),
                        @MetaValue(value = "LiteralInteger", targetEntity = LiteralIntegerImpl.class),
                        @MetaValue(value = "LiteralUnbounded", targetEntity = LiteralUnboundedImpl.class),
                        @MetaValue(value = "Expression", targetEntity = ExpressionImpl.class),
                        @MetaValue(value = "SequenceConstructionExpression", targetEntity = SequenceConstructionExpressionImpl.class),
                        @MetaValue(value = "QueryPathStepExpression", targetEntity = QueryPathStepExpressionImpl.class),
                }),
        @AnyMetaDef(name = "SequenceConstructionExpressionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "SequenceConstructionExpression", targetEntity = SequenceConstructionExpressionImpl.class),
                }),
        @AnyMetaDef(name = "RelationshipMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "FeatureTyping", targetEntity = FeatureTypingImpl.class),
                        @MetaValue(value = "ItemFlow", targetEntity = ItemFlowImpl.class),
                        @MetaValue(value = "ReturnParameterMembership", targetEntity = ReturnParameterMembershipImpl.class),
                        @MetaValue(value = "Import", targetEntity = ImportImpl.class),
                        @MetaValue(value = "FeatureMembership", targetEntity = FeatureMembershipImpl.class),
                        @MetaValue(value = "Generalization", targetEntity = GeneralizationImpl.class),
                        @MetaValue(value = "Subsetting", targetEntity = SubsettingImpl.class),
                        @MetaValue(value = "Membership", targetEntity = MembershipImpl.class),
                        @MetaValue(value = "Interaction", targetEntity = InteractionImpl.class),
                        @MetaValue(value = "ParameterMembership", targetEntity = ParameterMembershipImpl.class),
                        @MetaValue(value = "SuccessionItemFlow", targetEntity = SuccessionItemFlowImpl.class),
                        @MetaValue(value = "Superclassing", targetEntity = SuperclassingImpl.class),
                        @MetaValue(value = "Connector", targetEntity = ConnectorImpl.class),
                        @MetaValue(value = "Ownership", targetEntity = OwnershipImpl.class),
                        @MetaValue(value = "BindingConnector", targetEntity = BindingConnectorImpl.class),
                        @MetaValue(value = "Redefinition", targetEntity = RedefinitionImpl.class),
                        @MetaValue(value = "Succession", targetEntity = SuccessionImpl.class),
                        @MetaValue(value = "Association", targetEntity = AssociationImpl.class),
                        @MetaValue(value = "Multiplicity", targetEntity = MultiplicityImpl.class),
                        @MetaValue(value = "EndFeatureMembership", targetEntity = EndFeatureMembershipImpl.class),
                        @MetaValue(value = "FeatureValue", targetEntity = FeatureValueImpl.class),
                        @MetaValue(value = "Annotation", targetEntity = AnnotationImpl.class),
                        @MetaValue(value = "Relationship", targetEntity = RelationshipImpl.class),
                }),
        @AnyMetaDef(name = "ParameterMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "Parameter", targetEntity = ParameterImpl.class),
                }),
        @AnyMetaDef(name = "ItemFeatureMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "ItemFeature", targetEntity = ItemFeatureImpl.class),
                }),
        @AnyMetaDef(name = "QueryPathStepExpressionMetaDef", metaType = "string", idType = "java.util.UUID",
                metaValues = {
                        @MetaValue(value = "QueryPathStepExpression", targetEntity = QueryPathStepExpressionImpl.class),
                }),
})

// TODO Abstract this concept to cli option
@GenericGenerators(value = {
        @GenericGenerator(name = "UseExistingOrGenerateUUIDGenerator", strategy = "jpa.UseExistingOrGenerateUUIDGenerator")
})
package org.omg.sysml.metamodel.impl;

import org.hibernate.annotations.AnyMetaDef;
import org.hibernate.annotations.AnyMetaDefs;
import org.hibernate.annotations.MetaValue;

// TODO Abstract this concept to cli option
import org.hibernate.annotations.GenericGenerators;
import org.hibernate.annotations.GenericGenerator;